package com.board.dao;

public class BoardSQL {
	public static final String CREATE_TABLE =
			"""
				CREATE TABLE board (
				    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
				    title     VARCHAR2(255),
				    content   VARCHAR2(255),
				    type      VARCHAR2(255) CHECK (type IN ('NOTICE', 'DATA_ROOM', 'BOARD')),
				    author 	  VARCHAR2(255),
				    user_id   NUMBER,
				    file_id   NUMBER,
				    created_at DATE,
				    updated_at DATE,
				    del_yn CHAR(1) DEFAULT 'N' CHECK (del_yn IN ('Y', 'N'))
				    CONSTRAINT fk_board_user FOREIGN KEY (user_id) REFERENCES users(id),
				    CONSTRAINT fk_board_file FOREIGN KEY (file_id) REFERENCES files(id)
				)
			""";

	
	public static final String CREATE_BOARD = 
			"""
				INSERT INTO BOARD (title, content, type, user_id, file_id, created_at, updated_at, del_yn ,author) 
				VALUES (?, ?, ?, ?, ?, SYSDATE, SYSDATE, 'N', ?)
			""";

	
	public static final String GET_BOARD =
			"""
				SELECT * FROM BOARD WHERE id = ?
			""";

	
	public static final String GET_BOARD_FROM_TYPE =
			"""
				SELECT 
				    ROW_NUMBER() OVER (ORDER BY created_at DESC) AS no,
				    b.*
				FROM 
			    	BOARD b
				WHERE 
			    	type = ?
			""";
}