package com.board.dao;

public class CommentSQL {
	
//	public static final String CREATE_COMMENT_TABLE =
//			"""
//				CREATE TABLE comments (
//					    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
//					    board_id NUMBER NOT NULL,
//					    parent_id NUMBER DEFAULT 0,  -- 0이면 최상위 댓글, 아니면 대댓글
//					    author VARCHAR2(255) NOT NULL,
//					    content VARCHAR2(1000) NOT NULL,
//					    user_id NUMBER,
//					    created_at DATE DEFAULT SYSDATE,
//					    updated_at DATE DEFAULT SYSDATE,
//					    del_yn CHAR(1) DEFAULT 'N' CHECK (del_yn IN ('Y', 'N')),
//					    CONSTRAINT fk_comments_board FOREIGN KEY (board_id) REFERENCES board(id),
//					    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
//					)
//			""";
	
//	parent_id NUMBER DEFAULT 0,  -- 0이면 최상위 댓글, 아니면 대댓글
	
	public static final String CREATE_COMMENT_TABLE =
	"""
		CREATE TABLE comments (
			    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
			    board_id NUMBER NOT NULL,
			    parent_id NUMBER DEFAULT 0,  -- 0이면 최상위 댓글, 아니면 대댓글
			    author VARCHAR2(255) NOT NULL,
			    content VARCHAR2(1000) NOT NULL,
			    user_id NUMBER,
			    created_at DATE DEFAULT SYSDATE,
			    updated_at DATE DEFAULT SYSDATE,
			    del_yn CHAR(1) DEFAULT 'N' CHECK (del_yn IN ('Y', 'N'))
			)
	""";
    
    public static final String CREATE_COMMENT =
            """
            INSERT INTO comments (board_id, parent_id, author, content, user_id, created_at, updated_at, del_yn)
            VALUES (?, ?, ?, ?, ?, SYSDATE, SYSDATE, 'N')
            """;
    
    public static final String GET_COMMENTS_BY_BOARD_ID =
            """
            SELECT * FROM comments 
            WHERE board_id = ? AND del_yn = 'N'
            ORDER BY parent_id ASC, created_at ASC
            """;
    
    public static final String UPDATE_COMMENT =
            """
            UPDATE comments 
            SET content = ?, updated_at = SYSDATE 
            WHERE id = ? AND del_yn = 'N'
            """;
    
    public static final String DELETE_COMMENT =
            """
            UPDATE comments 
            SET del_yn = 'Y', updated_at = SYSDATE 
            WHERE id = ?
            """;
    
    public static final String DELETE_COMMENT_WITH_REPLIES =
            """
            UPDATE comments 
            SET del_yn = 'Y', updated_at = SYSDATE 
            WHERE id = ? OR parent_id = ?
            """;
}
